import assert from 'node:assert/strict';
import test from 'node:test';
import { UBUDDY_QCP_IHG_CAPABILITY, UBUDDY_QCP_IHG_VERSION, applyQcpIhgProjection, normalizeQcpIhgPrivateCommunicationMarker, normalizeQcpIhgProvenance, publicQcpIhgProjection, qcpIhgCompatibilityState, qcpIhgContentHash, sealQcpIhgProjection, stableQcpIhgProjectionId, validateQcpIhgProjection } from './uBuddyQcpIhg.js';

const sourceHash=qcpIhgContentHash({answer:'public'});
function projection(overrides={}) {
 const identity={senderUserId:'alice',recipientUserId:'bob',graphId:'graph-1',taskRunId:'task-1',ownerUserId:'alice',ownerUBuddyId:'ubuddy-alice',projectionRevision:2,sourceGraphRevision:7};
 identity.projectionId=stableQcpIhgProjectionId(identity);
 return sealQcpIhgProjection({version:UBUDDY_QCP_IHG_VERSION,capability:UBUDDY_QCP_IHG_CAPABILITY,identity,nodes:[{nodeId:'node-source',kind:'result',ownerUserId:'alice',title:'Result',publicSummary:'Public result'},{nodeId:'node-target',kind:'task',ownerUserId:'alice',title:'Downstream task'}],edges:[{edgeId:'edge-1',kind:'supports',fromNodeId:'node-source',toNodeId:'node-target'}],dependencyBundleRefs:[],workMemoryRefs:[],resultEvidenceRefs:[],releaseDecisions:[],completeness:'complete',permissions:{read:'recipient_only',write:'owner_ubuddy_only',readUserIds:['bob'],writeUserIds:['alice']},updatedAt:'2026-08-30T00:00:00.000Z',...overrides});
}
function released() {
 const b=projection(); return sealQcpIhgProjection({...b,releaseDecisions:[{decisionId:'decision-1',decision:'release',targetNodeId:'node-target',downstreamPurpose:'complete downstream task',relationEdge:{edgeId:'edge-1',kind:'supports',fromNodeId:'node-source',toNodeId:'node-target'},releaseReason:'accepted public result is required',privacyRiskExplanation:'reviewed public summary only',sourceObject:{objectId:'result-1',objectVersionId:'result-1-v1',ownerUserId:'alice',graphId:'graph-1',taskRunId:'task-1',contentHash:sourceHash},contentHash:sourceHash,allowedForRecipientOnly:true,provenance:{originalOwnerUserId:'alice',originalProjectionId:b.identity.projectionId}}]});
}
test('normal recipient projection validates',()=>{const r=validateQcpIhgProjection(projection(),{expectedSenderUserId:'alice',expectedRecipientUserId:'bob'});assert.equal(r.valid,true);});
test('missing identity and revisions are explicit',()=>{const r=validateQcpIhgProjection({version:UBUDDY_QCP_IHG_VERSION,capability:UBUDDY_QCP_IHG_CAPABILITY,identity:{},projectionHash:'0'.repeat(64)});assert.ok(r.errors.some(x=>x.code==='qcp_ihg_sender_recipient_required'));assert.ok(r.errors.some(x=>x.code==='qcp_ihg_scope_required'));assert.ok(r.errors.some(x=>x.code==='qcp_ihg_revision_invalid'));});
test('recipient and stable id mismatch rejected',()=>{const v=projection();v.identity.projectionId=stableQcpIhgProjectionId({...v.identity,recipientUserId:'carol'});const r=validateQcpIhgProjection(v,{expectedRecipientUserId:'carol'});assert.ok(r.errors.some(x=>x.code==='qcp_ihg_recipient_mismatch'));assert.ok(r.errors.some(x=>x.code==='qcp_ihg_projection_id_mismatch'));});
test('source hash and scope mismatch rejected',()=>{const v=released();v.releaseDecisions[0].sourceObject.contentHash=qcpIhgContentHash({answer:'changed'});v.releaseDecisions[0].sourceObject.graphId='other-graph';const r=validateQcpIhgProjection(v);assert.ok(r.errors.some(x=>x.code==='qcp_ihg_hash_conflict'));assert.ok(r.errors.some(x=>x.code==='qcp_ihg_scope_mismatch'));});
test('same revision different hash conflicts',()=>{const a=projection(),b=sealQcpIhgProjection({...a,publicSummary:'different'}),r=applyQcpIhgProjection(a,b);assert.equal(r.action,'hash_conflict');});
test('forwarding defaults false',()=>{const p=normalizeQcpIhgProvenance({originalOwnerUserId:'alice',originalProjectionId:'p1',forwardingAllowed:true});assert.equal(p.forwardingAllowed,false);assert.equal(p.recipientMayForward,false);const pub=publicQcpIhgProjection(projection());assert.equal(pub.permissions.recipientMayForward,false);assert.equal(pub.permissions.write,'none');});
test('private communication marker cannot enter public projection',()=>{const m=normalizeQcpIhgPrivateCommunicationMarker({communicationId:'chat-1',senderAgentId:'agent-a',recipientAgentId:'agent-b',taskRunId:'task-1'});assert.equal(m.publishable,false);const r=validateQcpIhgProjection(projection({privateCommunicationMarkers:[m]}));assert.ok(r.errors.some(x=>x.code==='qcp_ihg_private_communication_not_public'));assert.deepEqual(publicQcpIhgProjection({...projection(),privateCommunicationMarkers:[m]}).privateCommunicationMarkers,[]);});
test('private node and private memory ref are rejected',()=>{const v=projection({nodes:[{nodeId:'private-chat',kind:'summary',ownerUserId:'alice',contentClass:'private_communication'}],workMemoryRefs:[{id:'m1',versionId:'m1',visibility:'owner_private'}]});const r=validateQcpIhgProjection(v);assert.ok(r.errors.some(x=>x.code==='qcp_ihg_private_communication_not_public'));assert.ok(r.errors.some(x=>x.code==='qcp_ihg_work_memory_not_public'));});
test('payload limits report errors before truncation',()=>{const r=validateQcpIhgProjection({...projection(),publicSummary:'x'.repeat(4001),extra:{a:{b:{c:{d:{e:{f:{g:true}}}}}}}});assert.ok(r.errors.some(x=>x.code==='qcp_ihg_string_too_long'));assert.ok(r.errors.some(x=>x.code==='qcp_ihg_depth_exceeded'));});
test('legacy and mixed states explicit',()=>{assert.equal(qcpIhgCompatibilityState({}),'legacy');assert.equal(qcpIhgCompatibilityState({version:'ubuddy_collaboration_graph_v1'}),'mixed');assert.equal(qcpIhgCompatibilityState({version:UBUDDY_QCP_IHG_VERSION}),'qcp_ihg_v1');});
