export const SHARED_ENGLISH_EXACT = Object.freeze({
  '飞书连接服务尚未准备好。': 'The Feishu connection service is not ready.',
  '近期工作汇报功能尚未启用。': 'Recent work reporting is not enabled.',
  '本人补充': 'Owner Supplement',
  '请填写 App ID 和 App Secret。': 'Enter the App ID and App Secret.',
  '飞书连接尚未启动。': 'The Feishu connection has not started.',
  '文件': 'File',
  '补充所需信息': 'Provide More Information',
  '确认计划选项': 'Confirm Plan Options',
  '正在载入计划问题…': 'Loading plan questions…',
  '计划问题已失效，请返回主界面重试。': 'These plan questions have expired. Return to the main window and try again.',
  '查看主界面': 'View Main Window',
  '请输入你的回答': 'Enter your answer',
  '提交后 Janus 会继续当前任务。': 'Janus will continue the current task after you submit.',
  '选择只会细化计划，不会开始修改文件。': 'Your choices refine the plan and do not start modifying files.',
  '上一步': 'Back',
  '下一题': 'Next',
  '确认并继续生成计划': 'Confirm & Continue Planning',
  '正在提交…': 'Submitting…',
  '补充信息请求已经失效。': 'This request for more information has expired.',
  '推荐': 'Recommended',
  '其他': 'Other',
  '输入更符合你需求的方案': 'Enter an option that better matches your needs.',
  '请输入你的选择': 'Enter your choice',
  '正在启动 Janus': 'Starting Janus',
  '正在启动…': 'Starting…',
  '正在检查本地数据…': 'Checking local data…',
  '正在载入工作区…': 'Loading workspace…',
  '正在准备界面…': 'Preparing the interface…',
  'Janus 数据库恢复': 'Janus Database Recovery',
  '本地数据恢复': 'Local Data Recovery',
  'Janus 启动时检测到本地数据需要处理。': 'Janus found local data that needs attention before startup.',
  '退出 Janus': 'Quit Janus',
  '正在检查': 'Checking',
  '检查数据库状态': 'Check Database Status',
  '请稍候……': 'Please wait…',
  '重新检查': 'Check Again',
  '推荐操作': 'Recommended Action',
  '正在判断最安全的处理方式': 'Choosing the Safest Recovery Option',
  '所有更改都会先备份，并在副本中验证。': 'Every change is backed up first and verified on a copy.',
  '请稍候': 'Please Wait',
  '正在准备': 'Preparing',
  '高级恢复选项': 'Advanced Recovery Options',
  '手动修复': 'Manual Repair',
  '自动修复会先创建备份，再在副本上迁移和验证。': 'Automatic repair creates a backup, then migrates and verifies a copy.',
  '自动备份并修复': 'Back Up & Repair',
  '仅创建紧急备份': 'Create Emergency Backup Only',
  '可用备份': 'Available Backups',
  '恢复前仍会保留当前数据库的紧急副本。': 'An emergency copy of the current database is kept before recovery.',
  '隔离旧数据库': 'Quarantined Databases',
  '修复旧库并恢复聊天与 Agent Memory。': 'Repair an old database and restore chats and Agent Memory.',
  '最后兜底': 'Last Resort',
  '隔离旧数据库并创建干净的新数据库。旧数据不会被删除。': 'Quarantine the old database and create a clean one. Old data is not deleted.',
  '正在统计本地独有数据……': 'Reviewing local-only data…',
  '隔离旧库并使用新数据库': 'Quarantine Old Data & Use a New Database',
  '导出诊断': 'Export Diagnostics',
  '打开数据目录': 'Open Data Folder',
  '重新启动': 'Restart',
  '数据库健康': 'Database Healthy',
  '旧数据可恢复': 'Old Data Recoverable',
  '可以自动修复': 'Automatic Repair Available',
  '版本不兼容': 'Incompatible Version',
  '需要从备份恢复': 'Backup Recovery Required',
  '状态未知': 'Unknown Status',
  '本地数据库可以正常使用': 'The Local Database Is Ready',
  '当前新数据库健康，隔离旧数据仍可恢复': 'The New Database Is Healthy and Quarantined Data Can Be Restored',
  '检测到可修复的历史结构或脏数据': 'Repairable Legacy Structure or Inconsistent Data Detected',
  '需要更新 Janus 才能打开此数据库': 'Update Janus to Open This Database',
  '数据库无法通过安全检查': 'The Database Failed Safety Checks',
  '未知': 'Unknown',
  '当前数据库已通过完整性和一致性检查，之前的启动异常已经解除。': 'The database passed integrity and consistency checks. The previous startup issue is resolved.',
  '数据库已经可以正常使用': 'The Database Is Ready',
  '之前的错误已经不再阻止启动，重新进入 Janus 即可。': 'The previous error no longer blocks startup. Restart Janus to continue.',
  '重新进入 Janus': 'Restart Janus',
  '安全修复并继续使用': 'Repair Safely and Continue',
  '会先备份，再在副本中修复；聊天内容校验通过后才替换。': 'Janus backs up first, repairs a copy, and replaces the database only after chat validation passes.',
  '快速修复并重新启动': 'Quick Repair & Restart',
  '安装兼容版本后重新启动': 'Install a Compatible Version and Restart',
  '快速修复不可用': 'Quick Repair Unavailable',
  '旧聊天数据可以恢复': 'Old Chat Data Can Be Restored',
  '检测到多个隔离旧库，请在高级恢复选项中选择。': 'Multiple quarantined databases were found. Choose one under Advanced Recovery Options.',
  '恢复旧聊天并重新启动': 'Restore Old Chats & Restart',
  '选择旧数据库': 'Choose Old Database',
  '从最近备份恢复': 'Restore the Latest Backup',
  '需要手动处理数据库': 'Manual Database Recovery Required',
  '将使用最近的完整备份，当前数据库仍会保留紧急副本。': 'The latest complete backup will be used, and an emergency copy of the current database will be kept.',
  '请打开高级恢复选项导出诊断或使用最后兜底。': 'Open Advanced Recovery Options to export diagnostics or use the last-resort option.',
  '恢复最近备份并重新启动': 'Restore Latest Backup & Restart',
  '打开高级恢复选项': 'Open Advanced Recovery Options',
  '当前没有可用的验证备份。': 'No verified backups are available.',
  ' · 最近成功恢复点': ' · Latest Successful Recovery Point',
  '· 最近成功恢复点': '· Latest Successful Recovery Point',
  '最近成功恢复点': 'Latest Successful Recovery Point',
  '恢复此备份': 'Restore This Backup',
  '当前没有隔离旧数据库。': 'No quarantined databases are available.',
  ' · 已恢复过': ' · Previously Restored',
  '· 已恢复过': '· Previously Restored',
  '已恢复过': 'Previously Restored',
  '修复并恢复旧数据': 'Repair & Restore Old Data',
  '正在准备安全操作': 'Preparing the safe operation',
  '正在处理': 'Working',
  '操作失败': 'Operation Failed',
  '正在准备快速修复': 'Preparing quick repair',
  '恢复数据库备份': 'Restore Database Backup',
  '确定使用所选备份替换当前数据库吗？': 'Replace the current database with the selected backup?',
  '当前数据库会先保留为紧急副本。恢复后需要重新启动 Janus。': 'The current database will be kept as an emergency copy. Janus must restart after recovery.',
  '恢复': 'Restore',
  '使用全新数据库启动': 'Start with a New Database',
  '只有自动修复和备份恢复都无法解决问题时，才应使用此选项。': 'Use this option only if automatic repair and backup recovery both fail.',
  '隔离旧库并创建新库': 'Quarantine Old Data & Create New Database',
  '修复并恢复隔离旧数据库': 'Repair & Restore a Quarantined Database',
  '确定修复所选旧数据库并恢复聊天历史吗？': 'Repair the selected old database and restore its chat history?',
  '导出数据库诊断': 'Export Database Diagnostics',
  '选择要添加到对话的文件': 'Choose Files to Add to the Conversation',
  '添加到对话': 'Add to Conversation',
  '支持的文件': 'Supported Files',
  '保存文件': 'Save File',
  '保存计划': 'Save Plan',
  '导出诊断日志': 'Export Diagnostic Logs',
  '导出': 'Export',
  '选择项目': 'Choose Project',
  '选择项目工作区': 'Choose Project Workspace',
  '创建项目': 'Create Project',
  'Janus 启动失败': 'Janus Failed to Start',
  '应用启动失败，请重试。': 'The application failed to start. Please try again.',
  '正在载入任务工作区': 'Loading Task Workspace',
  '任务工作区视图': 'Task Workspace Views',
  '询问进度、查看验收原因、补充要求，或说“采用第 2 版”': 'Ask about progress, review acceptance details, add requirements, or say “Use version 2”.',
  'Word 文档': 'Word Document',
  '标题、段落、列表和表格': 'Headings, paragraphs, lists, and tables',
  '幻灯片、页面文本和版式内容': 'Slides, page text, and layout content',
  'PDF 文档': 'PDF Document',
  '页面和提取文本': 'Pages and extracted text',
  '表格文档': 'Spreadsheet',
  '工作表和单元格文本': 'Worksheets and cell text',
  '文本型文档': 'Text Document',
  '正文行': 'Text lines',
  '图片资源': 'Image Asset',
  '当前图像': 'Current image',
  '目标模式已开启': 'Goal Mode Is On',
  '发送下一条消息以设定持续目标，后续进度与状态会显示在这里。': 'Send your next message to set an ongoing goal. Progress and status will appear here.',
  '归档会话（保留消息、任务和文件）': 'Archive conversation while keeping messages, tasks, and files',
  '关闭创建群聊窗口': 'Close Create Group Chat',
  '例如 产品讨论组': 'For example: Product Discussion',
  '打开任务群共享文件工作区': 'Open the workgroup shared file workspace',
  '打开本任务的独立文件工作区': 'Open this task’s private file workspace',
  '任务执行仅可访问本任务工作区；超出范围的操作仍会请求批准': 'Task execution can access only this task workspace; out-of-scope actions still require approval.',
  '搜索模板...': 'Search templates...',
  'Janus 处理过程': 'Janus Activity',
  '文件差异': 'File Diff',
  '软件更新': 'Software Update',
  '更新完成': 'Update Complete',
  '更新公告': 'Update Notice',
  'Janus 更新日志': 'Janus Release Notes',
  '版本记录': 'Release History',
  '版本更新': 'Release Update',
  '更新内容': 'What Changed',
  '检测到更新时自动显示公告': 'Show update notices',
  '已运行': 'Completed',
  '已执行': 'Completed',
  '技术事件': 'Technical Events',
  '保留当前界面': 'Stay Here',
  '动态': 'Activity',
  '通讯录页面切换': 'Contacts Page Navigation',
  '移出已完成': 'Move Out of Completed',
  '标记为已完成': 'Mark as Completed',
  '已标记': 'Marked',
  'uBuddy 工作群': 'uBuddy Workgroup',
  ' · 需关注': ' · Needs Attention',
  '· 需关注': '· Needs Attention',
  ' · 等待同步': ' · Waiting to Sync',
  '· 等待同步': '· Waiting to Sync',
  '等待接收方处理': 'Waiting for the Recipient',
  '已进入 uBuddy 队列': 'Added to the uBuddy Queue',
  '处理': 'Process',
  '自己的 uBuddy 将协助整理并转达': 'Your uBuddy will organize and relay this message',
  '启用自己的 uBuddy 协助': 'Ask Your uBuddy to Help',
  '群共享工作区': 'Group Shared Workspace',
  '由我的 uBuddy 整理 · 仅自己可见': 'Organized by My uBuddy · Private',
  '仅自己可见': 'Private',
  '邀请与分享': 'Invitations & Sharing',
  '知道了': 'Got It',
  '例如 JANUS-2026': 'For example: JANUS-2026',
  '至少 6 个字符': 'At least 6 characters',
  '粘贴 janus://organization/join?...': 'Paste janus://organization/join?...',
  '例如 分布式系统实验室': 'For example: Distributed Systems Lab',
  '验证并重置': 'Verify & Reset',
  '群': 'Group',
  'uBuddy 团队简介': 'uBuddy Team Profile',
  '对方暂未公开可用简介': 'No Public Profile Available',
  '新增': 'Added',
  '字符': 'characters',
  '行': 'lines',
  '调整审阅区域宽度': 'Resize Review Area',
  '稍后': 'Later',
  '返回摘要': 'Back to Summary',
  '查看详细更新日志': 'View Detailed Release Notes',
  '正在启动安装，Janus 即将重启。': 'Starting installation. Janus will restart shortly.',
  '更新包已下载并通过校验，可以安装。': 'The update was downloaded and verified and is ready to install.',
  '更新可用，下载期间仍可继续使用 Janus。': 'An update is available. You can continue using Janus while it downloads.',
  '正在安装': 'Installing',
  '下载更新': 'Download Update',
  '安装并重启': 'Install & Restart',
  '数据库': 'Database',
  '加密': 'Encryption',
  '无需等待': 'No Waiting Required',
  '未知设备': 'Unknown Device',
  '当前设备': 'Current Device',
  '尚未评估': 'Not Evaluated Yet',
  '等待云端同步': 'Waiting for Cloud Sync',
  '无变更': 'No Changes',
  '就绪': 'Ready',
  '识别中': 'Identifying',
  '检查未通过': 'Checks Did Not Pass',
  '已置顶': 'Pinned',
  '置顶': 'Pin',
  '归档': 'Archive',
  '标题：': 'Title:',
  '已停用': 'Deactivated',
  '在线': 'Online',
  '告诉 Janus 应该如何调整': 'Tell Janus what to change',
  '问题导航': 'Question Navigation',
  '上一题': 'Previous Question',
  '我的 uBuddy': 'My uBuddy',
  '@我的uBuddy': '@My uBuddy',
  '支持 PNG / JPG / WEBP': 'Supports PNG / JPG / WEBP',
  'uBuddy 澄清问题': 'uBuddy Clarification',
  '请输入你的答案': 'Enter your answer',
  'uBuddy 等待用户回答': 'uBuddy Is Waiting for Your Answer',
  '已恢复': 'Recovered',
  '必须参与': 'Required',
  '当前未进入最终派发': 'Not Included in the Final Dispatch',
  'uBuddy 多人分工方案': 'uBuddy Collaboration Plan',
  '参与人': 'Participants',
  '全员参与': 'Everyone Participates',
  'Janus 技术事件': 'Janus Technical Events',
  '思考': 'Reasoning',
  '处理过程': 'Activity',
  '命令执行': 'Command Execution',
  '另存为': 'Save As',
  '新进展': 'New Activity',
  '这里仅属于你': 'This Space Is Private to You',
  '压缩上下文': 'Compress Context',
  '项目目录': 'Project Directory',
  '快捷功能': 'Quick Actions',
  '未命名项目': 'Untitled Project',
  '清空中…': 'Clearing…',
  '清空上下文': 'Clear Context',
  '当前上下文': 'Current Context',
  '项目工作区': 'Project Workspace',
  '无': 'None',
  '不使用模板': 'Do Not Use a Template',
  '通用页面库 · 无学校标识': 'General Slide Library · No School Branding',
  '学校模板 cover/body chrome': 'School template cover/body chrome',
  '补充要求': 'Add Requirements',
  '公开': 'Public',
  '启用': 'Enable',
  'Janus 用户': 'Janus User',
  '用户名': 'Username',
  '已验证': 'Verified',
  '未验证': 'Not Verified',
  '停用': 'Deactivate',
  '已招募': 'Recruited',
  '未招募': 'Not Recruited',
  '个人 Overlay 会继续保留，发生冲突时由你逐项选择。': 'Your personal overlay is preserved, and you choose how to resolve each conflict.',
  '例如：Janus Research Lab': 'For example: Janus Research Lab',
  '未填写用途': 'No Purpose Provided',
  '审核备注（可选）': 'Review Note (Optional)',
  '留空以保留本机 Key': 'Leave blank to keep the local key',
  '请输入 API Key': 'Enter API Key',
  '等待连接测试': 'Waiting for Connection Test',
  '未匹配': 'Not Matched',
  '尚未通过测试': 'Not Tested Successfully',
  '为空': 'Empty',
  '轨迹诊断': 'Trajectory Diagnosis',
  'Gate 裁决': 'Gate Decision',
  '应用与回归': 'Apply & Regression',
  'HR 复核': 'HR Review',
  '变动总结': 'Change Summary',
  '专家 agent 晋升': 'Specialist Agent Promotion',
  '生命周期候选': 'Lifecycle Candidates',
  '生命周期移出': 'Lifecycle Removal',
  '绩效考核': 'Performance Review',
  '部门 HR 审核': 'Department HR Review',
  '等待真实轨迹': 'Waiting for Real Trajectories',
  '稳态可推进': 'Ready to Proceed',
  '谨慎观察': 'Monitor Carefully',
  '需要介入': 'Intervention Required',
  '暂定': 'Provisional',
  '当前指标已满足，等待对应自动或治理流程。': 'Current metrics are satisfied; waiting for the applicable automated or governance process.',
  '请填写可审计的理由。': 'Provide an auditable reason.',
  '仅可在受控试岗中承担 task lead': 'May lead tasks only during a controlled trial',
  '支持跨部门与 cross-team lead': 'Eligible for cross-department and cross-team leadership',
  '独立执行者': 'Independent Contributor',
  '未填写申诉理由': 'No Appeal Reason Provided',
  '等待治理复核': 'Waiting for Governance Review',
  '重新启用': 'Reactivate',
  '专业执行': 'Specialist Performance',
  '扩展技能': 'Extended Skills',
  '未使用': 'Not Used',
  '当前使用': 'In Use',
  '招募后可选': 'Available After Recruitment',
  '退出 Canary': 'Leave Canary',
  '尚未使用': 'Not Used Yet',
  '可切换': 'Available',
  '只读归档': 'Read-only Archive',
  '活跃上下文': 'Active Context',
  '当前': 'Current',
  '切换': 'Switch',
  '项目上下文': 'Project Context',
  '常驻上下文': 'Persistent Context',
  '并发冲突': 'Concurrent Conflict',
  '主要记忆': 'Primary Memory',
  '独立执行者；正式带队前需要受控试岗。': 'Independent contributor; a controlled trial is required before formal leadership.',
  '已到顶级': 'Top Level Reached',
  '试岗申请等待 HR/治理审批': 'Leadership trial request awaiting HR/governance approval',
  '恢复申请等待治理审批': 'Restoration request awaiting governance approval',
  '申请 L1 受控试岗': 'Request L1 Controlled Trial',
  '申请 L2 team lead 试岗': 'Request L2 Team-Lead Trial',
  '申请 L3 跨部门试岗': 'Request L3 Cross-Department Trial',
  '已停止': 'Stopped',
  '键盘快捷键': 'Keyboard Shortcuts',
  '运行模式': 'Run Mode',
  '工作区': 'Workspace',
  '演示流程启动': 'Demo Workflow Started',
  '维护启动': 'Maintenance Started',
  '流程完成': 'Workflow Complete',
  '隐藏': 'Hide',
  '显示': 'Show',
  '申请已受理': 'Application Received',
  '领取完成': 'Claim Complete',
  '通路测试中': 'Testing Connection',
  '通路可用（有警告）': 'Connection Available (Warnings)',
  '通路测试通过': 'Connection Test Passed',
  '裁剪头像': 'Crop Avatar',
  '头像预览': 'Avatar Preview',
  '头像': 'Avatar',
  '跳过': 'Skip',
  '请选择一个选项，或输入自己的答案。': 'Choose an option or enter your own answer.',
  '重新': 'Again',
  '条': 'items',
  '双方将不再看到正文': 'Neither side will be able to view the content',
  '当前工作群': 'Current Workgroup',
  '· Ctrl/⌘+0 重置': '· Ctrl/⌘+0 Reset',
  '支持申诉': 'Approve Appeal',
  '驳回申诉': 'Reject Appeal',
  '已中止回答。': 'The response was stopped.',
  '当前运行环境不支持实时事件流。': 'This environment does not support live event streaming.',
  '记忆策略': 'Memory Policy',
  '衰减旧 typed memory，并应用生命周期策略。': 'Decay old typed Memory and apply lifecycle policies.',
  'Buddy agent 考核': 'Buddy Agent Review',
  '实验室招募研判': 'Lab Recruitment Review',
  '运行 regression eval runner。': 'Run the regression evaluation runner.',
  'Gate 校准': 'Gate Calibration',
  '维护完成': 'Maintenance Complete',
  '显示名不能为空。': 'Display name cannot be empty.',
  '请输入有效手机号。': 'Enter a valid phone number.',
  '日志目录尚未初始化。': 'The log directory has not been initialized.',
  '缺少项目工作目录。': 'The project working directory is missing.',
  '命令等待批准': 'Command Waiting for Approval',
  'Janus 已完成本地严格对照。': 'Janus completed the strict local comparison.',
  'Windows Sandbox 已就绪': 'Windows Sandbox Is Ready',
  '思考摘要': 'Reasoning Summary',
  'Token 使用量': 'Token Usage',
  '多个': 'Multiple',
  '处理通信与阻塞': 'Handle Communication and Blockers',
  '理解专业需求': 'Understand Specialist Requirements',
  '检查完整性、边界和可执行性': 'Check Completeness, Boundaries, and Feasibility',
  '理解问题': 'Understand the Request',
  '分析并分阶段回答': 'Analyze and Respond in Stages',
  '检查答案是否覆盖当前需求': 'Check Whether the Answer Covers the Request',
  '无权执行该 uBuddy 派发。': 'You do not have access to this uBuddy dispatch.',
  '缺少 uBuddy 派发命令 ID。': 'The uBuddy dispatch command ID is missing.',
  '发起人本地分工': 'Requester Local Assignment',
  '不支持的 uBuddy 派发类型。': 'This uBuddy dispatch type is not supported.',
  '处理已停止。': 'Processing was stopped.',
  '缺少项目 ID。': 'The project ID is missing.',
  '无权访问该项目。': 'You do not have access to this project.',
  '本次私有工作区处理已达到整体时限。': 'This private-workspace task reached its overall time limit.',
  'Janus agent 运行中': 'Janus Agent Running',
  'auth.json 必须是一个 JSON object。': 'auth.json must contain a JSON object.',
  '不支持的 Office 转换器。': 'This Office converter is not supported.',
  '缺少项目工作区。': 'The project workspace is missing.',
  '项目名称不能为空。': 'Project name cannot be empty.',
  '共享工作区同步参数不完整。': 'Shared-workspace sync parameters are incomplete.',
  '共享工作区中不允许使用符号链接，已停止同步。': 'Symbolic links are not allowed in shared workspaces. Sync was stopped.',
  '回退规划': 'Fallback Plan',
  '待分配': 'Unassigned',
  'uBuddy 简介审核决定无效。': 'The uBuddy profile review decision is invalid.',
  '当前候选不是可发布的最新最终汇总。': 'This candidate is not the latest publishable final summary.',
  'Hook 提示注入': 'Hook Prompt Injection',
  '工具调用': 'Tool Call',
  '资料检索': 'Research',
  '等待完成': 'Waiting for Completion',
  '进入审查模式': 'Enter Review Mode',
  '退出审查模式': 'Exit Review Mode',
  '你无权处理该退出申请。': 'You do not have access to handle this exit request.',
  '请输入群名。': 'Enter a group name.',
  '幂等键已被不同请求占用。': 'The idempotency key is already used by a different request.',
  '请选择有效用户。': 'Choose a valid user.',
  '撤销': 'Undo',
  '重做': 'Redo',
  '剪切': 'Cut',
  '粘贴': 'Paste',
  '全选': 'Select All',
  '第': 'Page',
  '页面缩略图': 'Page Thumbnails',
  '收起/展开缩略图': 'Collapse/Expand Thumbnails',
  ' · 预览已截断': ' · Preview Truncated',
  '· 预览已截断': '· Preview Truncated',
  '· 当前使用': '· Current',
  '· 暂定': '· Provisional',
  '展示 HR 如何根据证据推动候选、晋升、退休和结构治理。': 'See how HR uses evidence to manage candidates, promotions, retirement, and structural governance.',
  '工作中': 'Working',
  '已星标': 'Starred',
  '等待中': 'Waiting',
  '离线数据 ·': 'Offline Data ·',
  '我的 uBuddy · 协调整理': 'My uBuddy · Coordinated',
  '等待验收': 'Waiting for Acceptance',
  '已移动': 'Moved',
  '待决定': 'Waiting for Decision',
  '已启用': 'Enabled',
  '等待处理': 'Waiting for Processing',
  '等待启动': 'Waiting to Start',
  '已替换': 'Replaced',
  '命令执行 · 需检查': 'Command Execution · Needs Review',
  '命令执行 · 等待处理': 'Command Execution · Waiting',
  '原始命令': 'Raw Command',
  '等待检查': 'Waiting for Check',
  '等待选择': 'Waiting for Selection',
  '待运行': 'Waiting to Run',
  '策略 cluster_active_synced_mandatory_v1 · 单用户权重不超过 15% · 发布章节至少需要 3 位用户证据支持。': 'Policy cluster_active_synced_mandatory_v1 · Single-user weight is capped at 15% · Published sections require evidence from at least 3 users.',
  '验收返工': 'Acceptance Rework',
  '依赖协调': 'Dependency Coordination',
  '团队提升': 'Team Improvement',
  '当前用户': 'Current User',
  '试岗申请': 'Trial Request',
  '资格恢复': 'Eligibility Restoration',
  '降级': 'Demotion',
  '冻结': 'Freeze',
  '有效证据不足': 'Insufficient Valid Evidence',
  '评分未达到门槛': 'Score Below Threshold',
  '存在安全冻结': 'Safety Freeze Active',
  'team lead 试岗不足': 'Insufficient Team-Lead Trial Evidence',
  '跨团队试岗不足': 'Insufficient Cross-Team Trial Evidence',
  '团队效率提升证据不足': 'Insufficient Team-Efficiency Evidence',
  '团队效率提升低于 5%': 'Team-Efficiency Improvement Below 5%',
  '需要治理批准': 'Governance Approval Required',
  '已冻结': 'Frozen',
  '降级交接中': 'Demotion Handoff in Progress',
  '已降级': 'Demoted',
  '评估申诉': 'Evaluation Appeal',
  '晋升申诉': 'Promotion Appeal',
  '冻结申诉': 'Freeze Appeal',
  '降级申诉': 'Demotion Appeal',
  '申诉成立': 'Appeal Approved',
  '申诉驳回': 'Appeal Rejected',
  '本地可用 · 待同步': 'Available Locally · Waiting to Sync',
  '启用中 · 待同步': 'Enabling · Waiting to Sync',
  '需要处理冲突': 'Conflict Requires Attention',
  '本机已启用 · 云端待同步': 'Enabled Locally · Waiting for Cloud Sync',
  '已停用 · 云端待同步': 'Deactivated · Waiting for Cloud Sync',
  '专业领域': 'Specialist Domain',
  '默认参与': 'Participates by Default',
  '已退出': 'Opted Out',
  '会继续按默认策略参与': 'Will continue to participate under the default policy',
  '当前来源': 'Current Source',
  '兼容旧版组合': 'Legacy-Compatible Combination',
  '本版改动': 'Changes in This Version',
  '兼容问题': 'Compatibility Issues',
  '建立初始记忆结构': 'Create Initial Memory Structure',
  '常驻': 'Persistent',
  ' · 已冻结': ' · Frozen',
  '已审核': 'Reviewed',
  '待审核': 'Waiting for Review',
  '未审核': 'Not Reviewed',
  ' · 3 种风格': ' · 3 Styles',
  '项目已归档。': 'Project archived.',
  '本月': 'This Month',
  '分析用户意图、agent 响应质量、工具调用和记忆命中情况。': 'Analyze user intent, Agent response quality, tool calls, and Memory hits.',
  '定位到“技能步骤可细化、记忆策略需复核”的演示问题。': 'Identified a demo issue where Skill steps need refinement and the Memory policy needs review.',
  '演示草案通过 gate，未发现越权或隐私风险。': 'The demo draft passed the Gate with no privilege or privacy risks.',
  '模拟写入前快照、回归样例和变更验证。': 'Simulate pre-write snapshots, regression cases, and change validation.',
  'HR 视角检查是否需要候选、晋升、退休或职责迁移。': 'Review candidates, promotions, retirement, and responsibility changes from an HR perspective.',
  '演示流程完成': 'Demo Workflow Complete',
  '记忆生命周期策略已应用。': 'The Memory lifecycle policy was applied.',
  '已标记为有用演化。': 'Marked as a useful evolution.',
  '已标记为退化演化。': 'Marked as a regression.',
  '专家实验评估已完成。': 'Specialist experiment evaluation completed.',
  '专家已提升为正式 agent。': 'The specialist was promoted to a production Agent.',
  '简介预览功能当前未启用。': 'Profile preview is currently disabled.',
  '群内显示名不能超过 80 个字符。': 'The group display name cannot exceed 80 characters.',
  '新设备已批准，可领取 Device Grant。': 'The new device was approved and can claim a Device Grant.',
  '选择 agent': 'Choose Agent',
  '私人助理 · 本地隔离': 'Private Assistant · Local Isolation',
  '章节': 'Section',
  '等待上游依赖': 'Waiting for Upstream Dependencies',
  '已进入执行队列': 'Added to the Execution Queue',
  '依赖问题阻塞': 'Blocked by a Dependency Issue',
  '已拉黑用户。': 'User blocked.',
  '私助': 'Private',
  '当前云端已启用数据库安全协商，请升级 Janus 后再同步。': 'The cloud now requires database safety negotiation. Upgrade Janus before syncing.',
  '当前 Janus 的本地数据库结构与云端同步契约不兼容；同步已暂停，数据不会被写入，请先升级软件。': 'The local database structure is incompatible with the cloud Sync contract. Sync is paused and no data will be written until Janus is upgraded.',
  '准入考核': 'Admission Review',
  '论文/报告撰写': 'Paper/Report Writing',
  '跨部门综合': 'Cross-Department Synthesis',
  '跨部门证据与背景调研': 'Cross-Department Evidence and Background Research',
  '方法与评估设计': 'Method and Evaluation Design',
  '项目/申报工作': 'Project/Application Work',
  '阻塞通信请求': 'Blocking Communication Request',
  '阻塞通信测试': 'Blocking Communication Test',
  '@对方的uBuddy': '@Their uBuddy',
  '低': 'Low',
  '高': 'High',
  '最大': 'Maximum',
  '极致': 'Maximum',
  '哈工深模板': 'HITSZ Template',
  '华工模板': 'SCUT Template',
  '审批请求已经失效。': 'The approval request has expired.',
  '仅批准本次': 'Approve Once',
  '已完成路由': 'Routing Complete',
  '智能规划': 'Smart Planning',
  '此技能': 'This Skill',
  '项目名称': 'Project Name',
  '备注名称': 'Note Name',
  '等待恢复': 'Waiting for Recovery',
  '证据': 'Evidence',
  '等待上游依赖或新的工作要求。': 'Waiting for upstream dependencies or new work requirements.',
  '当前工作存在阻塞。': 'The current work is blocked.',
  '负责的工作已经完成。': 'The assigned work is complete.',
  '批准': 'Approve',
  '重新开放领取': 'Reopen Claims',
  '停止再次领取': 'Stop Further Claims',
  'auth.json 已格式化。': 'auth.json formatted.',
  'Janus 已完成模型服务配置，可直接使用': 'Janus has configured the model service and it is ready to use.',
  'Janus 已完成模型服务配置，可直接使用；如需自定义，请在下方填写并测试配置。': 'The Janus default model service is ready to use. To use your own Provider, enter the advanced configuration below, then save and test it before activation.',
  '如需使用自己的模型服务，请填写 config.toml 和 auth.json，保存并测试通过后生效': 'To use your own model service, fill in config.toml and auth.json. Your configuration will take effect after it is saved and passes the connection test.',
  '继续使用默认模型服务': 'Continue using the default model service',
  '当前继续使用默认模型服务。': 'Continue using the default model service.',
  '已恢复默认模型服务': 'Default Model Service',
  'config.toml 和 auth.json 已清空，可继续直接使用 Janus。': 'config.toml and auth.json were cleared. Janus has returned to the default model service.',
  'config.toml 需要完整的 model_provider/base_url，auth.json 需要对应认证变量；当前继续使用默认模型服务。': 'config.toml must define a complete model_provider and base_url, and auth.json must include the matching authentication variable. The custom Provider was not enabled; Janus will continue using the default model service.',
  '主进程未返回 Provider 测试结果；当前继续使用默认模型服务。': 'The Provider test returned no result from the main process. The custom Provider was not enabled; Janus will continue using the default model service.',
  '高级配置已清空，已恢复默认模型服务。': 'The advanced configuration was cleared and Janus has returned to the default model service.',
  '高级配置测试失败，将继续使用默认模型服务。': 'The advanced configuration test failed. The custom Provider was not enabled, and Janus will continue using the default model service.',
  '沟通请求已解决。': 'Communication request resolved.',
  '我 ·': 'Me ·',
  '· 已冻结': '· Frozen',
  '· 3 种风格': '· 3 Styles',
  '联': 'C',
  '中': 'Medium',
});

export function normalizeUiLanguage(value = '') {
  return String(value || '').toLowerCase().startsWith('zh') ? 'zh-CN' : 'en';
}

export function translateSharedUiText(value = '', language = 'en') {
  const source = String(value || '');
  if (normalizeUiLanguage(language) !== 'en') return source;
  return SHARED_ENGLISH_EXACT[source] || source;
}

export function uiText(zh, en, language = 'en') {
  return normalizeUiLanguage(language) === 'en' ? String(en || '') : String(zh || '');
}

export function englishErrorFallback(error = null) {
  const code = String(error?.code || error?.body?.error?.code || error?.body?.code || '').trim();
  return `The operation could not be completed.${code ? ` (${code})` : ''} Please try again.`;
}
