import { loadComposerFavoriteEmojis, loadComposerRecentEmojis, loadContactsListRatio, loadConversationZoomPercent, loadLanguageMode, loadMessagePanelWidth, loadNetworkDirectorySectionsOpen, loadPrivateAssistantPermission, loadRememberedLoginIdentifier, loadRunLogVisible, loadSandboxPermission, loadThemeMode } from './storage.js';

export const state = {
  languageMode: loadLanguageMode(),
  languageMenuOpen: false,
  appVersion: '0.1.0',
  appPackaged: false,
  updatedLaunch: false,
  root: '',
  workspaceRoot: '',
  org: { departments: [], agents: [], hrs: [] },
  sessions: [],
  projects: [],
  tasks: [],
  agentStatuses: [],
  evolution: null,
  uBuddyOrganizationEvolution: null,
  uBuddyOrganizationEvolutionBusy: '',
  currentUser: null,
  accountWorkspaces: [],
  activeAccountWorkspace: null,
  startupAccountWorkspace: null,
  uBuddyFeatureFlags: {
    version: 'ubuddy_feature_flags_v1',
    newTaskWorkspaceUi: true,
    newDispatchStrategy: true,
    newProcessEventStream: true,
    intakeClarificationV2: true,
    structuredTaskReference: true,
    profilePreviewV1: true,
    profilePreview: true,
    profileHistory: true,
    profilePublication: true,
    profileRoutingShadow: true,
    profileRoutingAuto: true,
    profileRoutingShadowV1: true,
    profileRoutingAutoV1: true,
    agentWorkDetailProjection: true,
    boundedDeliveryReworkV1: true,
    boundedDeliveryRework: true,
    messageModeV1: false,
    organizationEvolutionCollectV1: false,
    organizationEvolutionApplyV1: false,
    organizationEvolutionDecompositionV1: false,
  },
  uBuddyCapabilityProfilePreview: null,
  uBuddyCapabilityProfilePreviewLoading: false,
  uBuddyCapabilityProfilePreviewError: '',
  uBuddyCapabilityProfileHistory: null,
  uBuddyCapabilityProfileHistoryLoading: false,
  uBuddyCapabilityProfileHistoryError: '',
  uBuddyCapabilityProfileHistoryBusy: '',
  accountWorkspaceMenuOpen: false,
  accountMenuWorkspaceOpen: false,
  accountMenuWorkspaceMoreOpen: false,
  recentAccountWorkspaceIds: [],
  recentAccountWorkspaceUserId: '',
  workspaceSwitchBusy: false,
  workspaceSwitchTargetName: '',
  workspaceSwitchGeneration: 0,
  adminUsers: [],
  authMode: 'password',
  authScreen: 'login',
  authResetMode: 'email',
  authDraft: {
    loginPhone: '',
    loginEmail: '',
    loginCode: '',
    loginNewPassword: '',
    loginIdentifier: loadRememberedLoginIdentifier(),
    loginPassword: '',
    resetPhone: '',
    resetEmail: '',
    resetCode: '',
    resetNewPassword: '',
    registerName: '',
    registerEmail: '',
    registerCode: '',
    registerPassword: '',
    registerPasswordConfirm: '',
  },
  authFeedback: null,
  emailCodeNotice: null,
  emailCodeSending: null,
  emailCodeCooldowns: {},
  friendOverview: { friends: [], requests: { incoming: [], outgoing: [] } },
  socialInbox: [],
  socialThreads: [],
  preloadedMessagePagesBySessionId: {},
  networkPanelLoading: false,
  networkPanelError: '',
  socialStatus: null,
  networkConversationPeerId: '',
  networkConversationGroupId: '',
  networkDelegationId: '',
  networkConversationMessages: [],
  networkConversationBusy: false,
  networkConversationMode: 'person',
  networkConversationDrafts: {},
  socialMentionMenuOpen: false,
  composerMentionPickerMode: 'mention',
  uBuddyContactPickerOnly: false,
  secretaryMentions: [],
  composerMentions: [],
  messageReceiptPopover: null,
  composerTaskReference: null,
  uBuddyMessageMode: 'task',
  uBuddyParticipantSelectionPolicy: 'auto_select',
  uBuddyParticipantSelectionMenuOpen: false,
  taskReferenceMenuOpen: false,
  taskReferenceOptions: [],
  taskReferenceOptionsLoading: false,
  taskReferenceOptionsError: '',
  socialGroupSectionsOpen: { active: true, ended: true, archived: false },
  networkDelegationCommentDrafts: {},
  externalDelegationDeliveryDrafts: {},
  networkDelegationPendingMessages: {},
  networkDelegationSendQueuesById: {},
  networkDelegationQueueProcessingById: {},
  networkDelegationUBuddyEnabled: {},
  networkDelegationPublishedMessages: {},
  networkDelegationEditingMessageId: '',
  networkDelegationMemory: null,
  networkDelegationMemoryMenuOpen: false,
  networkDelegationRunsById: {},
  networkDelegationProgressById: {},
  networkDelegationTaskById: {},
  taskWorkspaceViewById: {},
  taskResultSubmissionById: {},
  collaborationGroupProgressOpenById: {},
  taskProgressOpenById: {},
  taskDisclosureOpenByKey: {},
  employeeActiveWorkCollapsedByInstanceId: {},
  uBuddyExpandedMessageIds: {},
  taskWorkspaceLoadingById: {},
  uBuddyTaskViewsById: {},
  uBuddyTaskViewLoadingById: {},
  uBuddyTaskViewErrorById: {},
  uBuddyTaskStripOpenBySessionId: {},
  uBuddyTaskStripFilterBySessionId: {},
  uBuddyTaskDrawerOpenBySessionId: {},
  uBuddyCenterOpen: '',
  uBuddyTaskCenterFilter: 'all',
  uBuddyTaskCenterQuery: '',
  uBuddyTaskCenterPage: null,
  uBuddyDeliveryCenterFilter: 'pending',
  uBuddyDeliveryCenterPage: null,
  uBuddyCenterLoading: false,
  uBuddyCenterError: '',
  uBuddyTaskUnseenBySessionId: {},
  messageViewStateByKey: {},
  secretarySessionId: '',
  agentDelegations: [],
  collaborationOverview: { groups: [], tasks: [] },
  chatGroupsOverview: { groups: [], capability: 'chat-groups-v2' },
  chatGroupId: '',
  chatGroupDetail: null,
  chatGroupDetailCache: {},
  chatGroupCreateOpen: false,
  chatGroupCreateBusy: false,
  chatGroupCreateTitle: '',
  chatGroupCreateMemberIds: [],
  chatGroupCreateLastMemberId: '',
  organizationNameEditId: '',
  organizationNameEditDraft: '',
  organizationNameEditBusy: false,
  collaborationGroupId: '',
  collaborationGroupDetail: null,
  collaborationGroupWorkspace: null,
  collaborationGroupWorkspaceBusy: false,
  collaborationPaneByGroupId: {},
  collaborationMobilePaneByGroupId: {},
  collaborationSearchOpen: false,
  collaborationSearchQuery: '',
  collaborationSearchActiveIndex: 0,
  collaborationMembersOpen: false,
  collaborationAutoOpenedDispatchIds: {},
  collaborationAddMemberOpen: false,
  collaborationAddMemberUserId: '',
  collaborationAddMemberAssignment: '',
  collaborationRoutingConfirmation: null,
  collaborationTaskId: '',
  collaborationTaskDrafts: {},
  collaborationTaskActionBusyById: {},
  networkBusyDelegationId: '',
  networkMessageSearchQuery: '',
  networkMessageSearchOpen: false,
  networkMessageSearchResultQuery: '',
  networkMessageSearchSessionIds: [],
  friendSearchQuery: '',
  networkDirectorySectionsOpen: loadNetworkDirectorySectionsOpen(),
  networkDirectoryKnownGroupIds: [],
  networkDirectoryGroupsInitialized: false,
  networkDirectoryNewGroupIds: [],
  networkSelectedContactId: '',
  networkSelectedContactOrganizationId: '',
  networkContactProfileOpen: false,
  chatAvatarProfile: null,
  uBuddyCapabilityProfilesByUserId: {},
  uBuddyCapabilityProfileLoadingByUserId: {},
  networkGroupProfileOpen: false,
  networkSelectedGroupKind: '',
  networkSelectedGroupId: '',
  groupDirectoryProfileDetail: null,
  groupDirectoryPreferences: { starred: {}, remarks: {} },
  chatGroupInviteOpen: false,
  chatGroupInviteBusy: false,
  chatGroupInviteUserId: '',
  chatGroupInviteGroupDetail: null,
  contactAddDialogOpen: false,
  contactAddDialogTab: 'contact',
  contactAddBusy: '',
  contactDirectoryContextMenu: null,
  directoryStars: { contacts: {}, employees: [] },
  friendDirectoryCategory: 'internal',
  contactGroupDirectoryTab: 'contact',
  friendDirectoryError: '',
  contactsActivePane: 'directory',
  friendSearchResults: [],
  friendSearchResultQuery: '',
  friendAddSearchQuery: '',
  friendDirectoryView: 'contacts',
  friendRequestActionId: '',
  friendRequestTargetId: '',
  friendRequestMessage: '',
  organizationJoinDraft: { organizationNumber: '', verificationCode: '', shareLink: '', setAsDefault: true },
  organizationCreateDraft: { name: '', organizationNumber: '', verificationCode: '' },
  contactsSelectedOrganizationId: '',
  organizationSettingsWorkspaceMoreOpen: false,
  organizationSettingsWorkspaceMorePosition: null,
  organizationActionDialog: null,
  organizationActionBusy: false,
  organizationSecondaryVerificationById: {},
  organizationShareLinks: {},
  organizationInvitePrompt: null,
  organizationInviteBusy: false,
  contactsListRatio: loadContactsListRatio(),
  socialEditDialog: null,
  modelMenuPlacement: { menu: 'right', submenu: 'left', vertical: 'above' },
  currentTab: 'chat',
  primaryChatReturnContext: null,
  taskWorkspaceReturnContext: null,
  activeTaskSourceContext: null,
  activeTaskReturnAnchorId: '',
  activeTaskReturnSurface: '',
  activeTaskReturnScrollTop: null,
  activeTaskWorkspaceKind: '',
  activeTaskWorkspaceId: '',
  taskRunWorkspaceMessagesById: {},
  taskRunWorkspaceDrafts: {},
  taskRunWorkspaceActiveRunById: {},
  sidebarMode: 'root',
  sidebarSectionsOpen: { tasks: true, collaboration: true, projects: false, chats: false },
  expandedProjectIds: [],
  activeProjectId: '',
  projectMenuOpenId: '',
  projectMenuKind: '',
  projectMenuPosition: null,
  currentSettingsSection: 'account',
  organizationResearchPolicy: null,
  organizationResearchAudits: null,
  organizationResearchLoading: false,
  organizationResearchError: '',
  organizationResearchBusy: false,
  organizationResearchResultsByMessageId: {},
  settingsSearchQuery: '',
  applicationLoggingStatus: null,
  applicationLoggingLoading: false,
  applicationLoggingError: '',
  applicationLoggingBusy: '',
  archivedSessions: null,
  archivedSessionsLoading: false,
  archivedSessionsError: '',
  currentSessionId: '',
  contextUsage: null,
  contextCompressionOperations: {},
  privateAssistantContextResetBusy: false,
  uBuddyConversationOpening: false,
  employeeMarketSpotlight: false,
  sessionMenuPosition: null,
  renameSessionDialog: null,
  memoryNameDialog: null,
  messages: [],
  uBuddyClarificationDrafts: {},
  messagePagination: { sessionId: '', source: '', nextCursor: null, hasMore: false, loading: false, initialLoading: false },
  messageContextMenu: null,
  messageEditingId: '',
  messageEditingDraft: '',
  messageEditingBusy: false,
  messageEditingError: '',
  messageQuote: null,
  messageForwardDialog: null,
  messageForwardBusy: '',
  currentDepartmentId: '',
  currentAgentId: '',
  currentAgentInstanceId: '',
  selectionSource: null,
  model: '',
  reasoningEffort: 'medium',
  modelCatalog: null,
  homeMode: 'department',
  sandboxPermission: loadSandboxPermission(),
  privateAssistantPermission: loadPrivateAssistantPermission(),
  sandboxMenuOpen: false,
  composerMetaOverflowOpen: false,
  composerToolMenuOpen: false,
  composerEmojiPickerOpen: false,
  composerEmojiTab: 'emoji',
  composerRecentEmojis: loadComposerRecentEmojis(),
  composerFavoriteEmojis: loadComposerFavoriteEmojis(),
  composerFavoriteManageOpen: false,
  composerFavoriteContextMenu: null,
  composerEmojiInsertionStart: null,
  composerEmojiInsertionEnd: null,
  uBuddyMessageModeMenuOpen: false,
  interactionMode: '',
  expandedGoalSessionIds: [],
  goalEditor: null,
  goalActionBusy: '',
  chatPlanViewer: null,
  composerImageMode: false,
  imageModel: 'gpt-image-2',
  pptTemplateId: 'none',
  pptTemplateMenuOpen: false,
  pptTemplateQuery: '',
  pptTemplatePreviewId: 'none',
  pptStyleId: 'general',
  pptStyleMenuOpen: false,
  agentMenuOpen: false,
  pendingWorkspaceRoot: '',
  workspaceDetached: false,
  workspaceMenuOpen: false,
  workspaceCreateMenuOpen: false,
  workspaceProjectQuery: '',
  composerMemoryMenuOpen: false,
  composerMemoryBusy: false,
  composerMemoryAgentInstanceId: '',
  composerMemoryDocuments: [],
  composerMemoryContext: null,
  composerFileReferences: [],
  composerMemoryReferences: [],
  composerMentionQuery: '',
  composerMentionActiveIndex: 0,
  composerMentionAnchorStart: 0,
  composerMentionAnchorEnd: 0,
  projectReferenceDirectory: '',
  projectReferenceEntries: [],
  projectReferenceLoading: false,
  projectReferenceError: '',
  projectReferenceProjectId: '',
  projectReferenceBrowseProjectId: '',
  attachments: [],
  preview: null,
  activeChatRun: null,
  chatRuns: [],
  chatPlanExecutionPrompt: null,
  agentDeliveryRunsBySession: {},
  privateAssistantResultUnread: false,
  currentChatKey: 'new-0',
  chatDraft: '',
  agentConversationDrafts: {},
  composerDraftsVersion: 2,
  composerDraftsBySurface: {},
  modelMenuOpen: false,
  modelSubmenuOpen: false,
  imageModelMenuOpen: false,
  busy: false,
  taskBusy: false,
  status: '',
  taskDetail: null,
  codexDoctor: null,
  codexConfig: null,
  codexConfigFiles: null,
  codexConnectionTest: null,
  feishuStatus: null,
  feishuLoading: false,
  feishuBusy: '',
  feishuTestResult: null,
  feishuDraft: null,
  codexConfigMode: 'fields',
  advancedModelServiceOpen: null,
  providerKeyApplicationDraft: { organization: '', usage: '' },
  providerKeyApplicationBusy: false,
  providerKeyApplicationResult: null,
  providerKeyEmailCode: '',
  providerKeyEmailVerificationBusy: false,
  providerKeyAccess: null,
  providerKeyAccessBusy: false,
  providerKeyDecisionBusyId: '',
  providerKeyClaimBusy: false,
  cloudSync: null,
  uploadCompliance: null,
  uploadComplianceLoading: false,
  uploadComplianceError: '',
  uploadComplianceBusyUserId: '',
  userAgentSettings: [],
  evolutionPreference: null,
  evolutionPreferenceLoading: false,
  evolutionPreferenceError: '',
  evolutionUpdates: null,
  evolutionUpdatesLoading: false,
  evolutionUpdatesError: '',
  personalEvolutionVersionsByAgent: {},
  personalEvolutionVersionLoadingId: '',
  personalEvolutionExpandedAgentIds: [],
  evolutionActionBusyKey: '',
  personalEvolutionStatus: null,
  stage8EvolutionStatus: null,
  clusterEvolutionOverview: { cohorts: [], runs: [], candidates: [] },
  clusterEvolutionRefreshBusy: false,
  evolutionGrants: [],
  personalEvolutionProposals: [],
  personalEvolutionProposalDetail: null,
  personalEvolutionBusy: false,
  personalEvolutionBusyInstanceId: '',
  employeeOverview: null,
  employeeOverviewError: '',
  agentWorkStatusByInstanceId: {},
  uBuddyCoordinationByTaskId: {},
  employeeBusyCommandId: '',
  employeeBusyTargetId: '',
  employeeBusyAction: '',
  employeeRefreshBusy: false,
  employeeMarketQuery: '',
  employeeMarketDepartmentFilter: 'all',
  employeeMarketStatusFilter: 'all',
  employeeMarketCandidateId: '',
  employeeMarketActionErrors: {},
  employeeContextMenu: null,
  employeeSelectedInstanceId: '',
  employeeDetailTab: 'overview',
  employeeMemoryDrawer: null,
  workMemoryObservability: null,
  employeeMarketDrawer: null,
  employeeGrowthDrawer: null,
  leadershipDecisionDialog: null,
  employeeConflict: null,
  employeeConversationOverviewByInstanceId: {},
  employeeConversationHistoryViewer: null,
  employeeLastRefreshAt: '',
  privateAssistant: null,
  managedProviderUsage: null,
  releaseDev: null,
  releaseStable: null,
  updates: null,
  agentUpdates: null,
  desktopLifecycle: {
    closeBehavior: '',
    defaultCloseBehavior: '',
    platform: globalThis.window?.janus?.platform || '',
    traySupported: false,
    trayActive: false,
    backgroundAvailable: false,
    lastError: '',
  },
  desktopLifecycleBusy: false,
  updateAnnouncementAutoPopup: true,
  updateAnnouncementLastSeenInstalledVersion: '',
  updateAnnouncementLastSeenAvailableVersion: '',
  updateAnnouncementDialog: null,
  updateAnnouncementInitialized: false,
  dryRunEvolution: false,
  evolutionScope: 'agents',
  evolutionSearchQuery: '',
  evolutionDetail: null,
  evolutionProgress: null,
  pluginSearchQuery: '',
  pluginFilter: 'all',
  pluginCategory: 'all',
  pluginSort: 'name',
  pluginSectionsOpen: { managed: null, attached: null, codex: null },
  pluginPageIndexes: { managed: 0, attached: 0, codex: 0 },
  pluginCatalog: [],
  codexPlugins: {
    capability: { supported: true, version: '', source: '', minimumVersion: '0.144.3', error: '', code: '' },
    installed: [], available: [], marketplaces: [], legacyMcpConflicts: [],
  },
  codexPluginBusy: '',
  codexPluginError: '',
  codexMarketplaceSource: '',
  attachedSkillCatalog: { packages: [], skills: [], assignments: [], targets: {} },
  attachedSkillImportSource: '',
  attachedSkillBusy: '',
  attachedSkillError: '',
  pluginOperations: {},
  pluginDetailId: '',
  pluginMenuOpenId: '',
  pluginReturnContext: null,
  pptxPluginStatus: null,
  pptxPluginStatusLoading: false,
  pluginInstalling: false,
  pluginInstallProgress: null,
  pluginUninstalling: false,
  pluginMenuOpen: false,
  pluginMenuPosition: null,
  sidebarCollapsed: false,
  runLogVisible: loadRunLogVisible(),
  notice: null,
  desktopDialog: null,
  themeMode: loadThemeMode(),
  networkPanelOpen: true,
  networkPanelView: 'messages',
  networkMessageHomeOpen: true,
  followerWorkspaceOpen: false,
  followerOwnerUserId: '',
  followerWorkspaceId: '',
  followerActiveSection: 'overview',
  followerSelectedKind: '',
  followerOverview: null,
  followerOverviewLoading: false,
  followerOverviewError: '',
  followerReports: [],
  followerRuns: [],
  followerReportFilter: 'all',
  followerSelectedReport: null,
  followerSelectedRun: null,
  followerSourceDrawer: null,
  followerSourceDrawerLoading: false,
  followerFollowup: null,
  followerFollowupBusy: false,
  followerFollowupDrafts: {},
  followerFormDraft: {},
  followerRailCollapsed: false,
  messageActivePane: 'list',
  responsiveLayoutMode: 'wide',
  messageDefaultVariantIndex: 0,
  messageDefaultVariantOrder: [0, 1, 2],
  messageDefaultOrderEditorOpen: false,
  messageGroupSidebarOpen: false,
  networkMessageListFilter: 'all',
  completedConversationKeys: [],
  completedConversationTimes: {},
  markedConversationKeys: [],
  unreadConversationKeys: [],
  conversationContextMenu: null,
  conversationZoomPercent: loadConversationZoomPercent(),
  messagePanelWidth: loadMessagePanelWidth(),
  selectedNetworkMessageId: '',
  chatSearchOpen: false,
  chatSearchQuery: '',
  chatSearchResults: [],
  chatSearchLoading: false,
  chatSearchError: '',
  collaborationImportingSessionId: '',
  collaborationSourcesOpen: false,
  sessionMenuOpenId: '',
  accountMenuOpen: false,
  draggingFiles: false,
};

export function isCurrentUserAdmin() {
  return state.currentUser?.role === 'admin' || state.currentUser?.is_admin === true || state.currentUser?.isAdmin === true;
}

export function currentUserPermissions() {
  return state.currentUser?.permissions || {};
}

export function roleLabel(role = state.currentUser?.role) {
  if (state.languageMode === 'en') return role === 'admin' ? 'Administrator' : 'Member';
  return role === 'admin' ? '管理员' : '普通成员';
}

export function userInitials(user = state.currentUser) {
  const text = user?.remark || user?.display_name || user?.displayName || user?.username || user?.email || user?.id || 'OP';
  return avatarLabelFromName(text);
}

export function avatarLabelFromName(value = '') {
  const text = String(value || '').trim();
  if (!text) return 'OP';
  const beforeEmail = text.split('@')[0] || text;
  const numericSuffix = beforeEmail.match(/(\d+)\s*$/);
  const stem = numericSuffix
    ? beforeEmail.slice(0, numericSuffix.index).replace(/[\s._-]+$/g, '')
    : beforeEmail;
  const compact = stem.replace(/[\s._-]+/g, '');
  const chinese = Array.from(compact.match(/[\u3400-\u9fff]/gu) || []);
  if (numericSuffix) {
    const digits = numericSuffix[1];
    if (digits.length >= 2) return digits.slice(-2);
    const words = stem.split(/[\s._-]+/).filter(Boolean);
    const leading = chinese[0] || Array.from(words[0] || compact)[0] || '';
    return `${leading}${digits}`.toUpperCase() || 'OP';
  }
  if (chinese.length >= 2) return chinese.slice(-2).join('');
  if (chinese.length === 1) return chinese[0];
  const words = stem.split(/[\s._-]+/).filter(Boolean);
  if (words.length >= 2) return words.slice(0, 2).map((part) => part[0]).join('').toUpperCase();
  return Array.from(compact || stem).slice(0, 2).join('').toUpperCase() || 'OP';
}
