#!/usr/bin/env python3
import argparse,json,pathlib,torch
from torch.nn.utils.rnn import pad_sequence
from datasets import load_dataset
from transformers import AutoTokenizer,AutoModelForCausalLM,BitsAndBytesConfig,TrainingArguments,Trainer
from peft import LoraConfig,get_peft_model,prepare_model_for_kbit_training
from tdb_completion import encode_completion
ap=argparse.ArgumentParser();ap.add_argument('--model',default='Qwen/Qwen3-8B');ap.add_argument('--dataset',required=True);ap.add_argument('--output_dir',required=True);ap.add_argument('--max_seq_length',type=int,default=4096);ap.add_argument('--per_device_train_batch_size',type=int,default=2);ap.add_argument('--gradient_accumulation_steps',type=int,default=16);ap.add_argument('--learning_rate',type=float,default=2e-4);ap.add_argument('--num_train_epochs',type=int,default=3);ap.add_argument('--lora_r',type=int,default=16);ap.add_argument('--lora_alpha',type=int,default=32);ap.add_argument('--lora_dropout',type=float,default=.05);ap.add_argument('--load_in_4bit',action='store_true');ap.add_argument('--bf16',action='store_true');a=ap.parse_args(); ds=load_dataset('json',data_files=a.dataset,split='train'); tok=AutoTokenizer.from_pretrained(a.model,trust_remote_code=True); tok.pad_token=tok.pad_token or tok.eos_token
def enc(x):
    return encode_completion(tok,x['prompt'],x['completion'],a.max_seq_length)
ds=ds.map(enc,remove_columns=ds.column_names); q=BitsAndBytesConfig(load_in_4bit=True,bnb_4bit_quant_type='nf4',bnb_4bit_compute_dtype=torch.bfloat16,bnb_4bit_use_double_quant=True) if a.load_in_4bit else None; m=AutoModelForCausalLM.from_pretrained(a.model,quantization_config=q,device_map='auto',torch_dtype=torch.bfloat16,trust_remote_code=True); m=prepare_model_for_kbit_training(m) if a.load_in_4bit else m; m=get_peft_model(m,LoraConfig(r=a.lora_r,lora_alpha=a.lora_alpha,lora_dropout=a.lora_dropout,target_modules=['q_proj','k_proj','v_proj','o_proj','gate_proj','up_proj','down_proj'],task_type='CAUSAL_LM')); m.print_trainable_parameters(); t=Trainer(model=m,args=TrainingArguments(output_dir=a.output_dir,num_train_epochs=a.num_train_epochs,per_device_train_batch_size=a.per_device_train_batch_size,gradient_accumulation_steps=a.gradient_accumulation_steps,learning_rate=a.learning_rate,bf16=a.bf16,logging_steps=10,save_strategy='epoch',report_to='none'),train_dataset=ds,data_collator=None); t.train(); t.save_model(a.output_dir); tok.save_pretrained(a.output_dir); (pathlib.Path(a.output_dir)/'training_contract.json').write_text(json.dumps({'assistant_only_loss':True,'prompt_tokens_masked':True,'max_seq_length':a.max_seq_length},indent=2)+'\n')
print(json.dumps({'output_dir':a.output_dir,'rows':len(ds),'assistant_only_loss':True}))
